### ISSUE TITLE
Trouble viewing .ipynb in GitHub

### ISSUE THREAD

**Issue by cheshireoctopus** [jakevdp/WhirlwindTourOfPython#1]
@jakevdp - really appreciate your intro to python w/ the focus on data sci. Am looking forward to picking up a copy of your handbook.

Having trouble viewing a few of the whirlwind tutorials in GitHub (might be them, not you).

So far, it looks as if the following pages are not rendering (I am able to read them by viewing the raw formats):

- https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/01-How-to-Run-Python-Code.ipynb
- https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/03-Semantics-Variables.ipynb
- https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/04-Semantics-Operators.ipynb
- https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/04-Semantics-Operators.ipynb
- https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/11-List-Comprehensions.ipynb

**Comment by jakevdp** [comment]
Github can sometimes be finicky for some reason. I'd try viewing them on nbviewer instead. Here's the nbviewer index, which links to all the other files: http://nbviewer.jupyter.org/github/jakevdp/WhirlwindTourOfPython/blob/master/Index.ipynb

**Comment by cheshireoctopus** [comment]
@jakevdp - appreciate the link :) thank you.
