### ISSUE TITLE
Question about continue

### ISSUE THREAD

**Issue by ajzeigert** [jakevdp/WhirlwindTourOfPython#2]
Hi, I am going through your (wonderful) Whirlwind Tour and got caught up on your explanation of the `continue` statement in part 7. The copy says you're using it to print a string of even numbers, but the string ends up being odd numbers. (And I _think_ the block is coded to produce odd numbers.) Am I missing something or is that just a typo?

I think what the code says is "if the remainder of dividing _n_ is 0, skip the rest of the loop". Is that what `continue` is for?

**Comment by jakevdp** [comment]
Hi – thanks for the feedback. Indeed, the "even" was a typo. I've changed that, and also made the comment more clear: https://github.com/jakevdp/WhirlwindTourOfPython/commit/604ef1d7056bf41196390b0d4d9feb3f60682528

Let me know if that clarifies things!

**Comment by ajzeigert** [comment]
👍 Thanks!
